Vagrant.require_version '>= 1.9.2'

Vagrant.configure(2) do |config|
  config.vm.box = 'debian'
  config.vm.guest = :linux
  config.vm.box_url = '../packed/debian.box'
  config.vm.box_check_update = false

  config.vm.provider :virtualbox do |vbox|
    vbox.name = 'debian'
  end

  config.vm.hostname = nil
  config.vm.network 'forwarded_port', guest: 80, host: 12346, protocol: 'tcp'
  config.vm.usable_port_range = 2200..2250

  config.vm.boot_timeout = 300
  config.vm.graceful_halt_timeout = 600
  config.vm.post_up_message = 'Vagrant is upped'

  config.vm.synced_folder 'www/', '/mnt/www/', :mount_options => ['dmode=777', 'fmode=666']
end
